[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  framework = "svelte-kit"
  targetPort = 5173

# For static assets
[[headers]]
  for = "/_app/immutable/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"
